builders:
  - script
triggers:
  cron: "@weekly"
slack:
  room: "devops-builds"
clean_workspace: true
build_in_docker:
  image: docker.sunet.se/sunet/docker-jenkins-node-job
archive_artifacts:
  include: ./*.js

extra_jobs:
  - name: docker-tumstock
    builders:
      - docker
    docker_name: tumstock
    managed_scripts:
      - docker_build_prep.sh
      - docker_tag.sh
    triggers:
      github_push: false
    upstream:
      - mdq-browser
    copy_artifacts:
      project_name: tumstock
      include: ./*.js
      target_dir: .
    archive_artifacts:

script:
  - "make setup all"
